// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("SillyXML")]
[assembly: AssemblyDescriptionAttribute("SillyXML - Immutable class XML serialization for the people!")]
[assembly: AssemblyProductAttribute("SillyXML")]
[assembly: AssemblyCopyrightAttribute("Copyright 2015 Fredrik Forssen")]
[assembly: AssemblyVersionAttribute("0.1.6")]
[assembly: AssemblyFileVersionAttribute("0.1.6")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.6";
    }
}
